name: CodeStyle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Change Default Rules
        run: |
          echo "
          [flake8]
          max-line-length = 120
          exclude =
              .git,
              .gitignore,
              .github,
              *.pot,
              *.py[co],
              __pycache__,
              venv,
              migrations,
              .env

          ignore =
              F403,
              F401" > .flake8
      - name: Run Tests
        run: |
          flake8
